### ISSUE TITLE
finalize vignettes

### ISSUE THREAD

**Issue by tdbennett** [CUD2V/pccc#16]
@jamesfeinstein and @tdbennett to edit the vignettes started by @dewittpe

**Comment by tdbennett** [comment]
vignette development is ongoing

**Comment by tdbennett** [comment]
@jamesfeinstein and @magic-lantern working on adding more discussion of rules used, potential traps if input codes are not properly formatted.

**Comment by tdbennett** [comment]
Nearing final versions of vignettes. Will be updated to reflect that most of the matching is by substring, but a few exact matches are done.

**Comment by magic-lantern** [comment]
Vignettes finalized
