### ISSUE TITLE
Update travis-ci and codecov

### ISSUE THREAD

**Issue by dewittpe** [CUD2V/pccc#21]
The repo ownership was transferred from @dewittpe to @CUD2V.  The `.travis.yml` and travis.org page needs to be set up. Please also update the badge shown in the README.md

**Comment by magic-lantern** [comment]
Looks like the URL is actually https://travis-ci.org for Travis CI.

Also, @dewittpe didn't mention this, but his personal account is also used for Codecov, so we should update that too.

**Comment by magic-lantern** [comment]
Updated readme and setup access for codecov and travis-ci to new repo location.
