### ISSUE TITLE
Submit package to CRAN

### ISSUE THREAD

**Issue by magic-lantern** [CUD2V/pccc#24]
I'm migrating the "Submit package to CRAN" issue originally tracked at magic-lantern/pccc#3 to this repo.

To see history of the issue, go to magic-lantern/pccc#3

Currently, main next steps are:
* Review code documentation, update as necessary (@magic-lantern, @tdbennett)
* Review vignettes, update as necessary (all contributors)
* Add Multiple Cause of Death Vignette (this task is currently assigned to @jamesfeinstein)

**Comment by magic-lantern** [comment]
Once on CRAN, update README with CRAN status badge like this:

`[![CRAN_Status_Badge](http://www.r-pkg.org/badges/version/pccc)](http://cran.r-project.org/package=pccc)`

**Comment by magic-lantern** [comment]
Actually looks like I can add the status badge now - just have to make sure it works correctly after publishing to CRAN.

**Comment by magic-lantern** [comment]
Following steps at: https://cran.r-project.org/web/packages/submission_checklist.html

As we're not quite yet ready to submit to CRAN, have submitted package to build services for testing:

- https://github.com/r-hub/rhub
- http://win-builder.r-project.org

No errors from the above so far.

**Comment by tdbennett** [comment]
Plan to submit to CRAN immediately prior to manuscript submission. If improvements from Debashis' class can be input by then, great, if not, no problem.

**Comment by magic-lantern** [comment]
Submitted to CRAN and accepted
