### ISSUE TITLE
Discrepancies and potential problems with current ICD code lists 

### ISSUE THREAD

**Issue by magic-lantern** [CUD2V/pccc#25]
This issue was originally opened as magic-lantern/pccc#1 - moving to new primary repo. Due to the number of potential issues with the ICD matching, I've copied the entire original post here.

Code fixes will be implemented by @magic-lantern, actual decisions to how each item will be resolved will be primarily made by @jamesfeinstein 

**ICD 9 duplicates** (are any of these mistakes and should actually be a different code?) 
* neuromusc_ccc dx 343 listed twice
* tech_dep_ccc dx T84498A, T86890, T86891, T86899 and are all listed twice
* transplant_ccc dx T86890, T86891, T86899 are all listed twice
* neuromusc_ccc dx G253 is listed twice

**ICD9 code discrepancies**
* neuromusc_ccc dx - includes 359 as well as 3590, 3591, 3592, 3593. Due to substring matching any code starting with 359 will match.
* Respiratory_CCC dx - includes 5163 as well as 51631.  Due to substring matching any code starting with 5163 will match.
* Metabolic CCC dx - 2359 metabolic should actually be 2539.
* Metabolic CCC pc - includes 624 as well as 6241. Due to substring matching, any code starting with 624 will match.
* The Stata version has several different codes not present in either the R version nor the SAS version: 
  * neuromusc_ccc dx: 3311, 3318
  * cardiovascular_ccc dx: 416
  * respiratory_ccc dx: 4160 

**There are several differences between SAS/R and Stata for ICD10 codes.** Here are the mismatches that I found
* Stata has 9782 as a neuromuscular ccc; SAS/R don’t have that code at all
* SAS/R have 9620 as a respiratory dx - Stata doesn’t have it anywhere.
* SAS/R have G3289 as a neuromuscular dx - Stata doesn't have that code at all.
* SAS/R have G4753 as a respiratory dx, Stata has G4735 (3/5 transposed)
* Stata has J9620 as a respiratory dx, SAS/R don’t have it at all.
* Stata has Q219, Q258, and Q259 as Cardiovascular dx, SAS/R don’t.
* Stata has Q851 as a NEUROMUSCULAR dx, SAS/R don’t.
* SAS/R have T82121A as a Cardiovascular and Tech_dep CCC, Stata doesn’t have it at all.

**There are also some ICD10 codes that could be problematic** - this is looking at the SAS file:

* hemato_immu_ccc dx: has D84 and metabolic_ccc has D841. Since D84 comes before D841 in the SAS file, D841 will never be categorized as a metabolic CCC.
* hemato_immu_ccc dx: has both D86 and D869. . Due to substring matching any code that starts D86 will be included.
* metabolic_ccc dx has E75 and neuromusc_ccc has E750, E751, E752, and E754. Due to ordering in the file, neuromuscular CCCs are flagged before the more general category E75 would be flagged as metabolic. 
* neuromusc_ccc dx: G318 and G3189 are both listed. Due to substring matching any code that starts G318 will be included.
* neuromusc_ccc dx: G80 and G803 are both listed. Due to substring matching any code that starts G80 will be included.
* I43 is listed as both a cvd_ccc dx and a respiratory_ccc dx. Since CVD comes first, I43 will never be classified as a respiratory CCC.

**General logic question:** For the procedure codes, I noticed that only respiratory_ccc is using “in:“ and all others are using “in” Doing substring matching for one group and not for the rest is quite a bit different than the ICD9 code logic. Is that what is wanted?

**Comment by tdbennett** [comment]
Waiting for final decisions on code discrepancies from Chris Feudtner. @magic-lantern to incorporate any code changes from those final decisions at that point.

**Comment by magic-lantern** [comment]
[CCC.V2.Issues_dai.docx](https://github.com/CUD2V/pccc/files/1475291/CCC.V2.Issues_dai.docx)

Brining over document from duplicate issue #32

**Comment by magic-lantern** [comment]
@jamesfeinstein  - It seems to me that we need to make a slight alteration to what Chris had highlighted, rather than modifying our existing logic.

It appears that an ICD code that has sub codes where some are CCCs and others are not CCCs should not be included. Additionally, it is my understanding that a code with subcodes isn't actually used - for example, no patient would actually have an ICD9CM dx code of 359, but would have 359.0 or 359.23.

E.g. although Chris highlighted all of the below for inclusion:

    359      muscular dystrophies*
    359.0    cong hered musc dystrphy
    359.1    hered prog musc dystrphy
    359.2    myotonic disorders#
    359.21   myotonic musclr dystrphy
    359.22   myotonia congenita
    359.23   myotonic chondrodystrphy
    359.29   myotonic disorder nec
    359.3    periodic paralysis

What we should actually match on is:

    359.0    cong hered musc dystrphy
    359.1    hered prog musc dystrphy
    359.21   myotonic musclr dystrphy
    359.22   myotonia congenita
    359.23   myotonic chondrodystrphy
    359.29   myotonic disorder nec
    359.3    periodic paralysis

Let me know your thoughts.

**Comment by jamesfeinstein** [comment]
This is exactly what we need to talk about. Chris and I discussed and he pointed out something specific to ICD codes in datasets that it will be easier for me to explain in person.


Take care,
Jamie
___________________________________________________

James A. Feinstein, MD MPH
Assistant Professor of Pediatrics, University of Colorado School of Medicine
Attending Physician, Children’s Hospital Colorado, Special Care Clinic & Child Health Clinic
Pediatric Director, Children’s Hospital Colorado Epidermolysis Bullosa Regional Program
Principal Investigator, Adult and Child Consortium for Health Outcomes Research and Delivery Science (ACCORDS)

For patient-related issues, please contact me at:
Special Care Clinic 720.777.6739<tel:720.777.6739> Phone | 720.777.7347<tel:720.777.7347> Fax

On Nov 15, 2017, at 09:08, Seth Russell <notifications@github.com<mailto:notifications@github.com>> wrote:


@jamesfeinstein<https://github.com/jamesfeinstein> - It seems to me that we need to make a slight alteration to what Chris had highlighted, rather than modifying our existing logic.

It appears that an ICD code that has sub codes where some are CCCs and others are not CCCs should not be included. Additionally, it is my understanding that a code with subcodes isn't actually used - for example, no patient would actually have an ICD9CM dx code of 359, but would have 359.0 or 359.23.

E.g. although Chris highlighted all of the below for inclusion:

359      muscular dystrophies*
359.0    cong hered musc dystrphy
359.1    hered prog musc dystrphy
359.2    myotonic disorders#
359.21   myotonic musclr dystrphy
359.22   myotonia congenita
359.23   myotonic chondrodystrphy
359.29   myotonic disorder nec
359.3    periodic paralysis


What we should actually match on is:

359.0    cong hered musc dystrphy
359.1    hered prog musc dystrphy
359.21   myotonic musclr dystrphy
359.22   myotonia congenita
359.23   myotonic chondrodystrphy
359.29   myotonic disorder nec
359.3    periodic paralysis


Let me know your thoughts.

**Comment by magic-lantern** [comment]
From Jamie: From Chris' experience, some datasets don't actually use a 4 digit (or longer code) so there are cases were CCC should do an exact match on a 3 digit code. While this will reduce performance, it should increase sensitivity (though reduce specificity).

**Comment by magic-lantern** [comment]
After reviewing the document and making code changes, I have a few questions:


1. If we do 3318, we’ll get the following codes - do we want all of these? R version currently only has 33189.
    ```
     icd_version code_type  code                          description
    1:           9        dx 33181                      Reye's syndrome
    2:           9        dx 33182            Dementia with lewy bodies
    3:           9        dx 33183 Mild cognitive impairment, so stated
    4:           9        dx 33189          Other cerebral degeneration
    ```

1. In the R version, we already have 33111 and 33119. As far as I can tell the only ICD codes that would match 3311 are the ones already in R. I have replaced 33111 and 33119 with 3311.


1. In reviewing the Word document and comments for “Stata has Q219, Q258, and Q259 as Cardiovascular dx, SAS/R don’t”, I noticed a problem with this section. The first line mentions code Q258, but the lookup below actually shows Q268. So do we actually want to include both Q258 and Q268?

1. Just want to make sure all G318 codes should be flagged as Neuromuscular CCCs (specific code matches weren’t shown in Word document as with other partial match questions).

```
> search_for_code(10, "^G318.*", "dx")
   icd_version code_type  code                                             description
1:          10        dx G3181                                          Alpers disease
2:          10        dx G3182                                         Leigh's disease
3:          10        dx G3183                               Dementia with Lewy bodies
4:          10        dx G3184                    Mild cognitive impairment, so stated
5:          10        dx G3185                               Corticobasal degeneration
6:          10        dx G3189 Other specified degenerative diseases of nervous system
```

**Comment by magic-lantern** [comment]
Another related question came up as I am working on implementing the fixed ICD code matching logic. All codes up to this point used substring matching, but now we'll have some of both.

What is the best way to convey to users of this application which codes are exact matches vs which codes are used in substring matching?

Currently there is a pccc::get_codes(icdver) function that returns all codes. We could manually maintain a list in a vignette that shows which codes are exact vs substring. Or, I could include both substring and fixed codes in get_codes() but provide additional functions such as get_fixed_codes() and get_substring_codes() that shows which codes are used in what manner. Another option could be to add a parameter to get_codes() to return the various groupings.

**Comment by magic-lantern** [comment]
Per today's discussion:

  * Should add 331 as substring match, remove all 331* codes.
  * include both Q258 and Q268
  * Include G318 as a substring match
  * modify get_codes() to include new elements: dx_fixed and pc_fixed for the fixed matches. @jamesfeinstein  to modify vignettes to explain new logic.

**Comment by magic-lantern** [comment]
Pushed commit e3e0ef94d14f39fca0dd1ed96ee6c8923c9f7981 that should address this issue and resolve all aspects.
