### ISSUE TITLE
Discussion/take home points

### ISSUE THREAD

**Issue by tdbennett** [CUD2V/pccc#27]
- R is free, open source, take advantage of package structure and documentation
- leveraging C++ back-end (proprietary software likely has, but this is explicit)
- benefits of collaborative code development/version control workflow
- @tdbennett to look for references, perhaps from ROpenSci post-doc looking at barriers

**Comment by tdbennett** [comment]
look at CompBio refs, submodule paper

**Comment by magic-lantern** [comment]
items included in research letter as appropriate.
