### ISSUE TITLE
CCC Version 2 Code Resolutions

### ISSUE THREAD

**Issue by jamesfeinstein** [CUD2V/pccc#32]
Document from Chris Feudtner attached with his decisions on code discrepancies. He highlighted codes that ARE CCCs and wrote his comments in CAPS. We will need to discuss strategy for implementing code for some of the substring issues, for example, ICD-9-CM 359*.
[CCC V2 Issues_dai.docx](https://github.com/CUD2V/pccc/files/1475073/CCC.V2.Issues_dai.docx)

**Comment by magic-lantern** [comment]
Already started in issue on this topic see #25
